In [2]:
import numpy as np


In [6]:
arr = np.array([1, 2, 3])
print(arr)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0, 4, 5)

array([0., 1., 2., 3., 4.])

In [21]:
np.random.rand(3, 2)

array([[0.71070343, 0.56484555],
       [0.68212348, 0.46229541],
       [0.15603753, 0.54361201]])

In [51]:
np.random.randn(3, 2)

array([[-0.72853345, -0.26890527],
       [ 1.68864286,  0.41159312],
       [ 1.5872747 ,  1.18319352]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [53]:
print(arr.shape)

(2, 3)


In [54]:
print(arr.ndim)

2


In [55]:
print(arr.size)

6


In [56]:
print(arr.dtype)

int64


In [58]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [59]:
a-b

array([-3, -3, -3])

In [60]:
a*b

array([ 4, 10, 18])

In [64]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [65]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [66]:
a@b

np.int64(32)

In [67]:
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [69]:
arr.mean()

np.float64(2.5)

In [70]:
arr.max()

np.int64(4)

In [72]:
arr.min()

np.int64(1)

In [74]:
arr.std()

np.float64(1.118033988749895)

In [77]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]
arr[1:4]
arr[::2]

array([1, 3, 5])

In [80]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0,1]
arr[:,1]
arr[1,:2]

array([4, 5])

In [83]:
arr = np.array([1, 2, 3, 4, 5])
mask=arr>3
arr[mask]

array([4, 5])

In [91]:
arr = np.arange(6)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
a=np.array([1,2])
b=np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [93]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [94]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [95]:
a=np.array([1,2,3])
a+5

array([6, 7, 8])

In [96]:
np.save('array.npy',arr)

In [98]:
loaded_arr=np.load('array.npy')
print(loaded_arr)

[0 1 2 3 4 5]
